### ISSUE TITLE
csrmesh should be version-pinned

### ISSUE THREAD

**Issue by antsar** [mjg59/python-avion#2]
The `csrmesh` dependency should be pinned to a compatible version. This module is not compatible with the latest version of csrmesh, and breaks on new installs.

```
>>> import avion
>>> dimmer = avion.avion('de:ad:be:ef:ba:be', 'MyAPIKey==')                                                                                                                                            
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "avion/__init__.py", line 38, in __init__
    self.password = csrmesh.network_key(password)
AttributeError: 'module' object has no attribute 'network_key'
```

## My environment
```
$ pip list
argparse (1.2.1)
avion (0.5, /home/anton/code/python-avion)
bluepy (1.0.5)
csrmesh (0.8.0)
pip (1.5.6)
pycrypto (2.6.1)
setuptools (5.5.1)
wsgiref (0.1.2)
```

**Comment by mjg59** [comment]
I've pushed a new version that works with current csrmesh and pins to that version.

**Comment by mjg59** [comment]
Thanks for the report!

**Comment by nkaminski** [comment]
I also do not plan to make such radical API changes to csrmesh moving forwards unless there is a **very** pressing reason to do so.
